environments:
  benrd: 
  bingrd:
  dev:
  prod-blue:
  prod-green: 
  prototype:


releases:

  - name: decd-cp-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/decd-client-portal
    namespace: decd-cp-{{ requiredEnv "BRANCH" }}
    values:
      - overrides/decd-client-portal.yaml.gotmpl
    labels:
        category: prototype
        app: decd-client-portal
        tier: frontend
    wait: false
    installed: true
    force: false